name: stats
dependencies:
  - python=3.11
  - pip:
    - numpy==1.26.4
    - pandas==2.2.1
    - matplotlib==3.8.3
    - tensorflow==2.16.1
    - scikit-learn==1.4.0
    - nibabel==5.2.1
    - scikit-image==0.22.0
    - pyarrow==15.0.2
    - ipykernel==6.29.3